# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25530bc0dde5d969704dff79fb269d9d48be5b95aaec8a49e4289e8f579f878f08ed58d874c0239d67c25fa008cb272b1e74dba699fa498a53ea89ac8c68ab2a

test:
  secret_key_base: 495261bc1d950fffee7fd2ce322538e2075234c5281b7e4cabc753d18d9302f618d87207af70dd2580d7b898ec67f9a10fe771ae7b9db62cf9fc30c302c1301a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
